#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("login.Resource", IsApplication=true)]

namespace login
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int addd = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bac2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int back = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int back1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int backg = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int backgr11 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int backgrlogin = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int backgrmenu = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int backtask1 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int beat = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int blood = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int calldoc = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int deobiet = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int diett = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int doctor = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int end1 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int fa1 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int fa2 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int four = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int gau = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int gaucon = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int gaunua = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int guild = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int hearth = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int history = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int huyetap = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Icon = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int it = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int itnguoi = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int loa = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int loca = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int logo = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int logout = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int map = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int mapdetail = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int mute = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int nhietdo = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int nhieunguoi = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int nhiptim = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int note = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int notee = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int one = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int over = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int pass = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int peo = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int phim = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int rel = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int remind = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int search = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int setting = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int take = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int tempera = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int them = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int three = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int two = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int video = 2130837559;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int ButtonBackbeat = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int ButtonBackcall1 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int ButtonBackcall2 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int ButtonBackdoctor = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int ButtonBackguild = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int ButtonBackhistory = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int ButtonBackmap = 2131034119;
			
			// aapt resource value: 0x7f05000f
			public const int ButtonBacknote = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int ButtonBackpress = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int ButtonBackremind = 2131034129;
			
			// aapt resource value: 0x7f050015
			public const int ButtonBacksetting = 2131034133;
			
			// aapt resource value: 0x7f05001e
			public const int ButtonBacktask = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int ButtonBacktem = 2131034143;
			
			// aapt resource value: 0x7f050008
			public const int add = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int beat = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int blood = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int button1 = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int doctor = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int family1 = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int family2 = 2131034126;
			
			// aapt resource value: 0x7f05001b
			public const int guild = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int history = 2131034138;
			
			// aapt resource value: 0x7f05001d
			public const int logout = 2131034141;
			
			// aapt resource value: 0x7f050016
			public const int map = 2131034134;
			
			// aapt resource value: 0x7f050018
			public const int note = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int remind = 2131034135;
			
			// aapt resource value: 0x7f05001c
			public const int setting = 2131034140;
			
			// aapt resource value: 0x7f050012
			public const int switch1 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int switch2 = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int switch3 = 2131034132;
			
			// aapt resource value: 0x7f05000d
			public const int tempera = 2131034125;
			
			// aapt resource value: 0x7f050019
			public const int tvdo = 2131034137;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int beat = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int call1 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int call2 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int doctor = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int guild = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int history = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int login = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int map = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int menu = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int note = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int pressure = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int remind = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int setting = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int task = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int temperature = 2130903054;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
